//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon May  6 11:34:43 2019 by ROOT version 6.06/08)
//      from the StreamerInfo in file /hepstore/burdin/data/lz_Miniproduction_1_lzap.root
//////////////////////////////////////////////////////////


#ifndef RQ__RQMCTruthEvent_h
#define RQ__RQMCTruthEvent_h
namespace RQ {
class RQMCTruthEvent;
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <string>

namespace RQ {
class RQMCTruthEvent : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int runNumber;    //
   unsigned int derEvent;     //
   unsigned int baccEvent;    //
   string       parentParticle;    //
   string       parentVolume;      //
   double       parentPositionX_mm;    //
   double       parentPositionY_mm;    //
   double       parentPositionZ_mm;    //
   double       parentEnergy_keV;      //
   double       parentDirectionX;      //
   double       parentDirectionY;      //
   double       parentDirectionZ;      //
   double       parentTime_ns;         //

   RQMCTruthEvent();
   RQMCTruthEvent(const RQMCTruthEvent & );
   virtual ~RQMCTruthEvent();

   ClassDef(RQMCTruthEvent,2); // Generated by MakeProject.
};
} // namespace
#endif
