//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon May  6 11:34:43 2019 by ROOT version 6.06/08)
//      from the StreamerInfo in file /hepstore/burdin/data/lz_Miniproduction_1_lzap.root
//////////////////////////////////////////////////////////


#ifndef RQ__Kr83mScatters_h
#define RQ__Kr83mScatters_h
namespace RQ {
class Kr83mScatters;
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <vector>

namespace RQ {
class Kr83mScatters : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         nKr83mScatters;    //Number of Kr83m-like interaction found in this event
   vector<int> s1aPulseID;        //ID of first S1 pulse
   vector<float> s1aArea_phd;       //[phd]; Total area of summed pod from start to end of first S1 pulse
   vector<int>   s1bPulseID;        //ID of second S1 pulse
   vector<float> s1bArea_phd;       //[phd]; Total area of summed pod from start to end of second S1 pulse
   vector<int>   s2PulseID;         //ID of S2 pulse
   vector<float> s2Area_phd;        //[phd]; Total area of summed pod from S2 pulse start to end
   vector<float> driftTime_ns;      //[ns]; Drift time
   vector<float> x_cm;              //[cm]; Reconstructed x-position of interaction
   vector<float> y_cm;              //[cm]; Reconstructed y-position of interaction
   vector<float> correctedX_cm;     //[cm]; Corrected x-position of interaction
   vector<float> correctedY_cm;     //[cm]; Corrected y-position of interaction
   vector<float> correctedZ_cm;     //[cm]; Corrected z-position of interaction
   vector<float> energy_keV;        //[keV]; Reconstructed energy of interaction

   Kr83mScatters();
   Kr83mScatters(const Kr83mScatters & );
   virtual ~Kr83mScatters();

   ClassDef(Kr83mScatters,2); // Generated by MakeProject.
};
} // namespace
#endif
