//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon May  6 11:34:43 2019 by ROOT version 6.06/08)
//      from the StreamerInfo in file /hepstore/burdin/data/lz_Miniproduction_1_lzap.root
//////////////////////////////////////////////////////////


#ifndef RQ__PileUpScatters_h
#define RQ__PileUpScatters_h
namespace RQ {
class PileUpScatters;
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;
namespace std {} using namespace std;

namespace RQ {
class PileUpScatters : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         nPileUpScatters;    //Number of pile up interactions found in this event
   vector<int> nS1;                //Number of S1s in pile up interaction
   vector<vector<int> > s1PulseIDs;         //IDs of S1 pulses
   vector<int>          nS2;                //Number of S2s in pile up interaction
   vector<vector<int> > s2PulseIDs;         //IDs of S2 pulses

   PileUpScatters();
   PileUpScatters(const PileUpScatters & );
   virtual ~PileUpScatters();

   ClassDef(PileUpScatters,2); // Generated by MakeProject.
};
} // namespace
#endif
