//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon May  6 11:34:43 2019 by ROOT version 6.06/08)
//      from the StreamerInfo in file /hepstore/burdin/data/lz_Miniproduction_1_lzap.root
//////////////////////////////////////////////////////////


#ifndef RQ__RQMCTruthVertices_h
#define RQ__RQMCTruthVertices_h
namespace RQ {
class RQMCTruthVertices;
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;

namespace RQ {
class RQMCTruthVertices : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         nRQMCTruthVertices;    //
   vector<string> volumeName;            //
   vector<string> particleName;          //
   vector<double> time_ns;               //
   vector<double> positionX_mm;          //
   vector<double> positionY_mm;          //
   vector<double> positionZ_mm;          //
   vector<double> electricFieldDirectionX;    //
   vector<double> electricFieldDirectionY;    //
   vector<double> electricFieldDirectionZ;    //
   vector<double> energyDep_keV;              //
   vector<unsigned int> rawS1Photons;               //
   vector<unsigned int> rawS2Photons;               //
   vector<unsigned int> rawScintPhotons;            //
   vector<unsigned int> s1PhotonHits;               //
   vector<unsigned int> s2PhotonHits;               //
   vector<unsigned int> scintPhotonHits;            //
   vector<unsigned int> detectedS1Photons;          //
   vector<unsigned int> detectedS2Photons;          //
   vector<unsigned int> detectedScintPhotons;       //
   vector<int>          s1PulseIndex;               //
   vector<int>          s2PulseIndex;               //
   vector<int>          scintillationPulseIndex;    //
   vector<vector<int> > artifactPulseIndices;       //

   RQMCTruthVertices();
   RQMCTruthVertices(const RQMCTruthVertices & );
   virtual ~RQMCTruthVertices();

   ClassDef(RQMCTruthVertices,2); // Generated by MakeProject.
};
} // namespace
#endif
