//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon May  6 11:34:43 2019 by ROOT version 6.06/08)
//      from the StreamerInfo in file /hepstore/burdin/data/lz_Miniproduction_1_lzap.root
//////////////////////////////////////////////////////////


#ifndef RQ__OtherScatters_h
#define RQ__OtherScatters_h
namespace RQ {
class OtherScatters;
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;

namespace RQ {
class OtherScatters : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         nOtherScatters;    //Number of other interactions in Event
   vector<int> nS1s;              //Number of S1s
   vector<vector<int> > s1PulseIDs;        //S1 pulse IDs
   vector<int>          nS2s;              //Number of S2s
   vector<vector<int> > s2PulseIDs;        //S2 pulse IDs
   vector<int>          nSPEs;             //Number of Single Photoelectrons (SPEs)
   vector<vector<int> > spePulseIDs;       //SPE pulse IDs
   vector<int>          nSEs;              //Number of single electrons (SEs)
   vector<vector<int> > sePulseIDs;        //SE pulse IDs
   vector<int>          nOthers;           //Number of other pulses
   vector<vector<int> > otherPulseIDs;     //Other pulse IDs

   OtherScatters();
   OtherScatters(const OtherScatters & );
   virtual ~OtherScatters();

   ClassDef(OtherScatters,2); // Generated by MakeProject.
};
} // namespace
#endif
