//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon May  6 11:34:43 2019 by ROOT version 6.06/08)
//      from the StreamerInfo in file /hepstore/burdin/data/lz_Miniproduction_1_lzap.root
//////////////////////////////////////////////////////////


#ifndef RQ__RQMCTruthPulses_h
#define RQ__RQMCTruthPulses_h
namespace RQ {
class RQMCTruthPulses;
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;
namespace std {} using namespace std;

namespace RQ {
class RQMCTruthPulses : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         nRQMCTruthPulses;    //
   vector<unsigned short> pulseIdentifier;     //
   vector<int>            vertexNumber;        //
   vector<unsigned int>   pheCount;            //
   vector<double>         firstPheTime_ns;     //
   vector<double>         lastPheTime_ns;      //
   vector<vector<unsigned short> > pmtIndices;          //
   vector<vector<unsigned int> >   pmtHits;             //

   RQMCTruthPulses();
   RQMCTruthPulses(const RQMCTruthPulses & );
   virtual ~RQMCTruthPulses();

   ClassDef(RQMCTruthPulses,2); // Generated by MakeProject.
};
} // namespace
#endif
