//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon May  6 11:34:43 2019 by ROOT version 6.06/08)
//      from the StreamerInfo in file /hepstore/burdin/data/lz_Miniproduction_1_lzap.root
//////////////////////////////////////////////////////////


#ifndef RQ__EventHeader_h
#define RQ__EventHeader_h
namespace RQ {
class EventHeader;
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <string>

namespace RQ {
class EventHeader : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned long eventID;     //event ID, taken from globalEvt
   string        rawFileName;    //file that this event belongs to
   unsigned long triggerTimeStamp_s;    //seconds component of trigger time (POSIX)
   unsigned long triggerTimeStamp_ns;    //ns component of trigger time (ns past triggerTimeStamp_s)

   EventHeader();
   EventHeader(const EventHeader & );
   virtual ~EventHeader();

   ClassDef(EventHeader,2); // Generated by MakeProject.
};
} // namespace
#endif
