//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon May  6 11:34:43 2019 by ROOT version 6.06/08)
//      from the StreamerInfo in file /hepstore/burdin/data/lz_Miniproduction_1_lzap.root
//////////////////////////////////////////////////////////


#ifndef RQ__RQMCDarkCounts_h
#define RQ__RQMCDarkCounts_h
namespace RQ {
class RQMCDarkCounts;
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <vector>

namespace RQ {
class RQMCDarkCounts : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         nRQMCDarkCounts;    //
   vector<unsigned short> pmtIndex;           //
   vector<double>         time_ns;            //

   RQMCDarkCounts();
   RQMCDarkCounts(const RQMCDarkCounts & );
   virtual ~RQMCDarkCounts();

   ClassDef(RQMCDarkCounts,2); // Generated by MakeProject.
};
} // namespace
#endif
